// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/fakovacic/users-service/internal/users"
	"sync"
)

// Ensure, that StoreMock does implement users.Store.
// If this is not the case, regenerate this file with moq.
var _ users.Store = &StoreMock{}

// StoreMock is a mock implementation of users.Store.
//
// 	func TestSomethingThatUsesStore(t *testing.T) {
//
// 		// make and configure a mocked users.Store
// 		mockedStore := &StoreMock{
// 			CreateFunc: func(contextMoqParam context.Context, user *users.User) error {
// 				panic("mock out the Create method")
// 			},
// 			DeleteFunc: func(contextMoqParam context.Context, s string) error {
// 				panic("mock out the Delete method")
// 			},
// 			GetFunc: func(contextMoqParam context.Context, s string) (*users.User, error) {
// 				panic("mock out the Get method")
// 			},
// 			ListFunc: func(contextMoqParam context.Context, meta *users.Meta) (int64, []*users.User, error) {
// 				panic("mock out the List method")
// 			},
// 			UpdateFunc: func(contextMoqParam context.Context, s string, user *users.User) error {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedStore in code that requires users.Store
// 		// and then make assertions.
//
// 	}
type StoreMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(contextMoqParam context.Context, user *users.User) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(contextMoqParam context.Context, s string) error

	// GetFunc mocks the Get method.
	GetFunc func(contextMoqParam context.Context, s string) (*users.User, error)

	// ListFunc mocks the List method.
	ListFunc func(contextMoqParam context.Context, meta *users.Meta) (int64, []*users.User, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(contextMoqParam context.Context, s string, user *users.User) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// User is the user argument value.
			User *users.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
		}
		// List holds details about calls to the List method.
		List []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Meta is the meta argument value.
			Meta *users.Meta
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// S is the s argument value.
			S string
			// User is the user argument value.
			User *users.User
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
	lockUpdate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *StoreMock) Create(contextMoqParam context.Context, user *users.User) error {
	if mock.CreateFunc == nil {
		panic("StoreMock.CreateFunc: method is nil but Store.Create was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		User            *users.User
	}{
		ContextMoqParam: contextMoqParam,
		User:            user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(contextMoqParam, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedStore.CreateCalls())
func (mock *StoreMock) CreateCalls() []struct {
	ContextMoqParam context.Context
	User            *users.User
} {
	var calls []struct {
		ContextMoqParam context.Context
		User            *users.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *StoreMock) Delete(contextMoqParam context.Context, s string) error {
	if mock.DeleteFunc == nil {
		panic("StoreMock.DeleteFunc: method is nil but Store.Delete was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(contextMoqParam, s)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedStore.DeleteCalls())
func (mock *StoreMock) DeleteCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *StoreMock) Get(contextMoqParam context.Context, s string) (*users.User, error) {
	if mock.GetFunc == nil {
		panic("StoreMock.GetFunc: method is nil but Store.Get was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(contextMoqParam, s)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedStore.GetCalls())
func (mock *StoreMock) GetCalls() []struct {
	ContextMoqParam context.Context
	S               string
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *StoreMock) List(contextMoqParam context.Context, meta *users.Meta) (int64, []*users.User, error) {
	if mock.ListFunc == nil {
		panic("StoreMock.ListFunc: method is nil but Store.List was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Meta            *users.Meta
	}{
		ContextMoqParam: contextMoqParam,
		Meta:            meta,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(contextMoqParam, meta)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockedStore.ListCalls())
func (mock *StoreMock) ListCalls() []struct {
	ContextMoqParam context.Context
	Meta            *users.Meta
} {
	var calls []struct {
		ContextMoqParam context.Context
		Meta            *users.Meta
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *StoreMock) Update(contextMoqParam context.Context, s string, user *users.User) error {
	if mock.UpdateFunc == nil {
		panic("StoreMock.UpdateFunc: method is nil but Store.Update was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		S               string
		User            *users.User
	}{
		ContextMoqParam: contextMoqParam,
		S:               s,
		User:            user,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(contextMoqParam, s, user)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedStore.UpdateCalls())
func (mock *StoreMock) UpdateCalls() []struct {
	ContextMoqParam context.Context
	S               string
	User            *users.User
} {
	var calls []struct {
		ContextMoqParam context.Context
		S               string
		User            *users.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
